{% set name = "sidetable" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d98b43f038107a901e867bb60296ec8af2ee689b12d413931859fd9023ac9ce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pandas >=1.0
    - python

test:
  imports:
    - sidetable
  requires:
    - pytest
    - seaborn

about:
  home: https://github.com/chris1610/sidetable
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sidetable builds simple but useful summary tables of your data

extra:
  recipe-maintainers:
    - chris1610
